import { useRef } from 'react';
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import CardActionArea from '@mui/material/CardActionArea';
import CardContent from '@mui/material/CardContent';
import Container from '@mui/material/Container';
import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';
import Head from 'next/head';
import Link from 'next/link';

import BaseLayout from '@/components/BaseLayout';
import useWindowSize from '@/hooks/useWindowSize';
import sitemap from '@/sitemap';

export default function Home() {
  const containerRef = useRef<HTMLDivElement>(null);
  const { height: windowHeight } = useWindowSize();

  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <BaseLayout
        sx={{
          height: windowHeight || '100vh',
          px: 3,
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <Container maxWidth="lg" ref={containerRef}>
          <Stack
            spacing={3}
            display="flex"
            justifyContent="center"
            alignSelf="center"
          >
            <Stack
              spacing={1}
              sx={{
                mb: 5,
                display: 'flex',
                justifyContent: 'center',
                alignSelf: 'center',
              }}
            >
              <Typography
                component="div"
                variant="h1"
                sx={{ alignSelf: 'center' }}
              >
                Mark Kopani
              </Typography>
              <Typography
                component="div"
                variant="h3"
                sx={{ alignSelf: 'center' }}
              >
                Full Stack Web3 Developer
              </Typography>
            </Stack>
            {/* Site options */}
            <Stack
              direction={{ xs: 'column', sm: 'row' }}
              spacing={1.5}
              sx={{
                display: 'flex',
                justifyContent: 'center',
                alignItems: 'center',
                alignSelf: 'center',
                width: { xs: '100%', md: '65%' }
              }}
            >
              {Object.entries(sitemap).map(([route, name]) => (
                <Box key={route} width="100%">
                  <SectionCard
                    name={name}
                    href={route}
                  />
                </Box>
              ))}
            </Stack>
          </Stack>
        </Container>
      </BaseLayout>
    </>
  );
}

const SectionCard = ({ name, href }: { name: string; href: string }) => {
  const blurEffect = 'blur(8px)';

  return (
    <Link href={href} passHref style={{ textDecoration: 'none' }}>
      <Card
        sx={{
          backgroundColor: 'rgba(255, 255, 255, 0.025)',
          borderRadius: 3,
          width: '100%',
          backdropFilter: blurEffect,
          backgroundBlendMode: 'overlay',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          transition: '0.3s',
          '&:hover': {
            transform: 'scale(1.05)'
          },
        }}
      >
        <CardActionArea disableRipple disableTouchRipple>
          <CardContent
            sx={{
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
            }}
          >
            <Typography variant="h5" sx={{ fontWeight: 400 }}>
              {name}
            </Typography>
          </CardContent>
        </CardActionArea>
      </Card>
    </Link>
  );
};
